### ISSUE TITLE
Game crashes because of "conductiveMap" being null

### ISSUE THREAD

**Issue by espmancer** [Apothicon02/Create-Molten-Vents#6]
**Crashlog:** The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "com.Apothic0n.MoltenVents.core.objects.ActiveMoltenBlockEntity.conductiveMap" is null

**Version:** 1.20.1

I was using an active molten vent block by itself, and it crashes most of the time.

**Comment by Apothicon02** [comment]
This is most likely caused by an incorrectly made datapack, provide log.

**Comment by Apothicon02** [comment]
Also if you do want to fix it you should ask for support in the discord instead, I rarely will check these github issue things.
